=== riccardopersiani/DP2_Assignement1/dtd/nffgInfo.dtd
<!-- DTD for a System that manages NFFGs and Catalog -->
<!ELEMENT RootNetwork (NFFG+)>

<!ELEMENT NFFG (Nodes, Links, Policies)>
<!ATTLIST NFFG
	NFFG_name ID #REQUIRED	
	last_update_time CDATA #REQUIRED	
>	

<!ELEMENT Nodes (Node+) >

<!ELEMENT Links (Link+) >

<!ELEMENT Policies (Policy+) >

<!ELEMENT Node (Service) >
<!ATTLIST Node
	node_name ID #REQUIRED		
>
<!ELEMENT Link (Source, Destination)>
<!ATTLIST Link
	link_name ID #REQUIRED		
>	
<!ELEMENT Policy (ReachabilityPolicy | TraversalPolicy)>
<!ATTLIST Policy
	policy_name ID #REQUIRED
>	
	
<!ELEMENT Service EMPTY>
<!ATTLIST Service
	service_name (Firewall | DPI | Mail_client | Mail_server | Web_client | Web_server | Anti_spam | NAT | VPN_gateway | Web_cache)	#REQUIRED	
>	

<!ELEMENT Source EMPTY>
<!ATTLIST Source
	source_name IDREF #REQUIRED		
>		
<!ELEMENT Destination EMPTY>
<!ATTLIST Destination
	destination_name IDREF #REQUIRED			
>
<!ELEMENT ReachabilityPolicy (Source , Destination)>
<!ATTLIST ReachabilityPolicy
	verification_result (true | false) #IMPLIED
	verification_time CDATA #IMPLIED
	verification_message CDATA #IMPLIED
	isPositive	(true | false)	#REQUIRED				
>
<!ELEMENT TraversalPolicy (Source, Destination, Devices)>	
<!ATTLIST TraversalPolicy
	verification_result (true | false) #IMPLIED
	verification_time CDATA #IMPLIED
	verification_message CDATA #IMPLIED
	isPositive	(true | false)	#REQUIRED				
>
<!ELEMENT Devices (Device+)>

<!ELEMENT Device EMPTY>
<!ATTLIST Device	
	service_name (Firewall | DPI | Mail_client | Mail_server | Web_client | Web_server | Anti_spam | NAT | VPN_gateway | Web_cache) #REQUIRED 		
>
<!-- Must use the char "-" to separate words, otherwise it will display an error -->	

<!-- Using IDREFs will introduce the difficulty to manage them inside the DTD but it the application side will be easier -->
		
<!-- This DTD has been developed by Riccardo Persiani s225289 
		for the assignment 1 of the Distributed Programming II course -->

=== riccardopersiani/DP2_Assignement1/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RootNetwork SYSTEM "nffgInfo.dtd" >

<RootNetwork>

	<NFFG NFFG_name="NFFG1" last_update_time="2016-09-27T03:26:20.000+02:00">
		<Nodes>
			<Node node_name="NODE1">
				<Service service_name="NAT" />
			</Node>
			<Node node_name="NODE2">
				<Service service_name="Firewall" />
			</Node>
			<Node node_name="NODE3">
				<Service service_name="DPI" />
			</Node>
		</Nodes>
		<Links>
			<Link link_name="LINK1">
				<Source source_name="NODE1" />
				<Destination destination_name="NODE2" />
			</Link>
			<Link link_name="LINK2">
				<Source source_name="NODE2" />
				<Destination destination_name="NODE1" />
			</Link>
			<Link link_name="LINK3">
				<Source source_name="NODE2" />
				<Destination destination_name="NODE3" />
			</Link>

			<Link link_name="LINK4">
				<Source source_name="NODE3" />
				<Destination destination_name="NODE2" />
			</Link>
		</Links>
		<Policies>
			<Policy policy_name="POLICY1">
				<ReachabilityPolicy isPositive="true">
					<Source source_name="NODE1" />
					<Destination destination_name="NODE3" />
				</ReachabilityPolicy>
			</Policy>
			<Policy policy_name="POLICY2">
				<ReachabilityPolicy verification_message="Ok" verification_time="2016-09-27T03:26:20.000+02:00" verification_result="true" isPositive="true">
					<Source source_name="NODE2" />
					<Destination destination_name="NODE1" />
				</ReachabilityPolicy>
			</Policy>
			<Policy policy_name="POLICY3">
				<TraversalPolicy verification_message="Ok" verification_time="2016-09-27T03:26:20.000+02:00" verification_result="false" isPositive="false">
					<Source source_name="NODE3" />
					<Destination destination_name="NODE1" />
					<Devices>
						<Device service_name="NAT" />
						<Device service_name="Firewall" />
					</Devices>
				</TraversalPolicy>
			</Policy>
		</Policies>
	</NFFG>
	<NFFG NFFG_name="NFFG2" last_update_time="2016-09-27T03:26:20.000+02:00">
		<Nodes>
			<Node node_name="NODE4">
				<Service service_name="NAT" />
			</Node>
			<Node node_name="NODE5">
				<Service service_name="Mail_client" />
			</Node>
			<Node node_name="NODE6">
				<Service service_name="DPI" />
			</Node>
		</Nodes>
		<Links>
			<Link link_name="LINK5">
				<Source source_name="NODE4" />
				<Destination destination_name="NODE5" />
			</Link>
			<Link link_name="LINK6">
				<Source source_name="NODE5" />
				<Destination destination_name="NODE5" />
			</Link>
			<Link link_name="LINK7">
				<Source source_name="NODE6" />
				<Destination destination_name="NODE5" />
			</Link>
			<Link link_name="LINK8">
				<Source source_name="NODE6" />
				<Destination destination_name="NODE6" />
			</Link>
		</Links>
		<Policies>
			<Policy policy_name="POLICY4">
				<ReachabilityPolicy isPositive="true">
					<Source source_name="NODE6" />
					<Destination destination_name="NODE4" />
				</ReachabilityPolicy>
			</Policy>
			<Policy policy_name="POLICY5">
				<ReachabilityPolicy verification_message="Ok" verification_time="2016-09-27T03:26:20.000+02:00" verification_result="true" isPositive="true">
					<Source source_name="NODE4" />
					<Destination destination_name="NODE5" />
				</ReachabilityPolicy>
			</Policy>
			<Policy policy_name="POLICY6">
				<TraversalPolicy  isPositive="true">
					<Source source_name="NODE4" />
					<Destination destination_name="NODE5" />
					<Devices>
						<Device service_name="Mail_client" />
					</Devices>
				</TraversalPolicy>
			</Policy>
			<Policy policy_name="POLICY7">
				<TraversalPolicy verification_message="Ok" verification_time="2016-11-20T11:00:00" verification_result="false" isPositive="false">
					<Source source_name="NODE3" />
					<Destination destination_name="NODE1" />
					<Devices>
						<Device service_name="NAT" />
						<Device service_name="NAT" />
						<Device service_name="Firewall" />
					</Devices>
				</TraversalPolicy>
			</Policy>
		</Policies>
	</NFFG>
</RootNetwork>
