=== riccardopersiani/DP2_Assignement1/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		xmlns="http://www.riccardopersiani.com/Schema"
		xmlns:nffg="http://www.riccardopersiani.com/Schema"
        targetNamespace="http://www.riccardopersiani.com/Schema"
        elementFormDefault="qualified">

	<xsd:element name="RootNetwork" type="nffg:RootNetworkType">	
		<!-- the (id) of [NFFG] must be globally unique -->
		<xsd:unique name="oneNffgForEachNffgId"> 
			<xsd:selector xpath="nffg:NFFG"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<!-- (id) in [Policy] must be globally unique -->
		<xsd:unique name="onePolicyforEachPolicyId"> 
			<xsd:selector xpath="nffg:NFFG/nffg:Policies/*"/>
			<xsd:field xpath="@id"/>
		</xsd:unique>				
	</xsd:element>
		
	<xsd:complexType name="RootNetworkType"> <!-- RootNetwork uses this type -->
		<xsd:sequence>
			<xsd:element name="NFFG" type="nffg:NFFGType" maxOccurs="unbounded">
				<!-- (id) in [Node] must be unique locally, inside the NFFG -->
				<!-- The *KEY* is the attribute (id) in [Node], which is in {Nodes} -->  
				<xsd:key name="NodeKey">
					<xsd:selector xpath="nffg:Nodes/nffg:Node"/>
					<xsd:field xpath="@id"/>
				</xsd:key>
				<!-- The KEYREF is the element (Source) present [Link] ->(id)[Node] -->
				<xsd:keyref name="SourceLinkKeyRef" refer="nffg:NodeKey">
					<xsd:selector xpath="nffg:Links/nffg:Link"/>
					<xsd:field xpath="nffg:Source"/>
				</xsd:keyref>
				<!-- The KEYREF is the element (Destination) present [Link] ->(id)[Node]-->		
				<xsd:keyref name="DestinationLinkKeyRef" refer="nffg:NodeKey">
					<xsd:selector xpath="nffg:Links/nffg:Link"/>
					<xsd:field xpath="nffg:Destination"/>
				</xsd:keyref>
				<!-- The KEYREF is the element (Source) present [ReachabilityPolicy] ->(id)[Node] -->
				<xsd:keyref name="SourceReachabilityPolicyKeyRef" refer="nffg:NodeKey">
					<xsd:selector xpath="nffg:Policies/nffg:ReachabilityPolicy"/>
					<xsd:field xpath="nffg:Source"/>
				</xsd:keyref>
				<!-- The KEYREF is the element (Destination) present [ReachabilityPolicy] ->(id)[Node] -->
				<xsd:keyref name="DestinationReachabilityPolicyKeyRef" refer="nffg:NodeKey">
					<xsd:selector xpath="nffg:Policies/nffg:ReachabilityPolicy"/>
					<xsd:field xpath="nffg:Destination"/>
				</xsd:keyref>		
				<!-- (id) in [Link] must be unique locally, inside the NFFG -->
				<xsd:unique name="oneLinkforEachLinkID"> 
					<xsd:selector xpath="nffg:Links/nffg:Link"/>
					<xsd:field xpath="@id"/>
				</xsd:unique>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="NFFGType"> <!-- NFFG uses this type -->
		<xsd:sequence>
			<xsd:element name="Nodes" type="nffg:NodesType"/>
			<xsd:element name="Links" type="nffg:LinksType"/> 
			<xsd:element name="Policies" type="nffg:PoliciesType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="nffg:InitialCharType" use="required"/>
		<xsd:attribute name="last_update_time" type="xsd:dateTime" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="NodesType">
		<xsd:sequence>
			<xsd:element name="Node" type="nffg:NodeType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="LinksType">
		<xsd:sequence>
				<xsd:element name="Link" type="nffg:LinkType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="PoliciesType">
		<xsd:sequence>
			<xsd:element name="ReachabilityPolicy" type="nffg:ReachabilityPolicyType" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="TraversalPolicy" type="nffg:TraversalPolicyType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="InitialCharType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z]([a-zA-Z0-9])*"/>
		</xsd:restriction>
	</xsd:simpleType>
			
	<xsd:complexType name="NodeType"> <!-- Node uses this type -->
		<xsd:sequence>
			<xsd:element name="Service" type="nffg:ServiceType"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="nffg:InitialCharType" use="required"/>			
	</xsd:complexType>
	
	<xsd:complexType name="LinkType"> <!-- Link uses this type -->
		<xsd:sequence>
			<xsd:element name="Source" type="xsd:string" /> 
			<xsd:element name="Destination" type="xsd:string"/> 
		</xsd:sequence>
		<xsd:attribute name="id" type="nffg:InitialCharType" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="ReachabilityPolicyType"> <!-- Policy uses this type -->
		<xsd:sequence>
			<xsd:element name="Source" type="xsd:string" /> 
			<xsd:element name="Destination" type="xsd:string"/>
			<xsd:element name="isPositive" type="xsd:boolean"/>
			<xsd:element name="Verification" type="nffg:VerificationType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="nffg:InitialCharType" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="TraversalPolicyType">
		<xsd:complexContent>
			<xsd:extension base="nffg:ReachabilityPolicyType">
				<xsd:sequence>
					<xsd:element name="Devices" type="nffg:DevicesListType"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
		
	<xsd:complexType name="VerificationType"> <!-- Verification uses this type -->
		<xsd:sequence>
			<xsd:element name="Time" type="xsd:dateTime" minOccurs="0"/>
			<xsd:element name="Message" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Result" type="xsd:boolean" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>	
	
	<xsd:complexType name="DevicesListType">
		<xsd:sequence>
			<xsd:element name="Device" type="nffg:ServiceType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
		
	<xsd:simpleType name="ServiceType"><!-- SingleService in Catalog uses this type -->
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Firewall"/>
			<xsd:enumeration value="DPI"/>
			<xsd:enumeration value="NAT"/>
			<xsd:enumeration value="Anti-spam"/>
			<xsd:enumeration value="Web-cache"/>
			<xsd:enumeration value="VPN gateway"/>
			<xsd:enumeration value="Web server"/>
			<xsd:enumeration value="Web client"/>
			<xsd:enumeration value="Mail server"/>
			<xsd:enumeration value="Mail client"/>
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== riccardopersiani/DP2_Assignement1/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE xml>
<RootNetwork xmlns="http://www.riccardopersiani.com/Schema"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.riccardopersiani.com/Schema file:///C:/Users/Riccardo/workspace/DP2_Assignement1/xsd/nffgInfo.xsd"
		 >
	
	<NFFG name="NFFG1">
	
		<Nodes>
			<Node id="Node1">
				<Service>NAT</Service>
			</Node>
			<Node id="Node2">
				<Service>Mail client</Service>
			</Node>
			<Node id="Node3">
				<Service>DPI</Service>
			</Node>
			<Node id="Node4">
				<Service>Mail server</Service>
			</Node>
		</Nodes>
		<Links>
			<Link id="Link1">
				<Source>Node1</Source>
				<Destination>Node2</Destination>			
			</Link>
			<Link id="Link2">
				<Source>Node2</Source>
				<Destination>Node2</Destination>			
			</Link>
			<Link id="Link2">
				<Source>Node3</Source>
				<Destination>Node4</Destination>			
			</Link>
			<Link id="Link2">
				<Source>Node3</Source>
				<Destination>Node4</Destination>			
			</Link>
		</Links>	
		<Policies>
			<ReachabilityPolicy id="r1">
				<Source>Node2</Source>
				<Destination>Node3</Destination>
				<isPositive>true</isPositive>
				<Verification>
					<Time>2016-10-24T13:00:00</Time>
					<Message>Ok</Message>
					<Result>true</Result>
				</Verification> 
			</ReachabilityPolicy>
		
			<TraversalPolicy id="t1">
				<Source>Node2</Source>
				<Destination>Node3</Destination>
				<isPositive>false</isPositive>			
				<Verification>
					<Time>2016-10-24T13:00:00</Time>
					<Message>Ok</Message>
					<Result>false</Result>
				</Verification> 
				<Devices>
					<Device>Mail server</Device>
					<Device>NAT</Device>
					<Device>Firewall</Device>
					<Device>DPI</Device>
				</Devices>
			</TraversalPolicy>
		</Policies>
	</NFFG>
	
	<Catalog>
		<SingleService name="Firewall"/>
		<SingleService name="Web-cache"/>
		<SingleService name="NAT"/>
		<SingleService name="VPN gateway"/>
		<SingleService name="Anti-spam"/>
		<SingleService name="Mail client"/>
		<SingleService name="Mail server"/>
		<SingleService name="Web client"/>
		<SingleService name="Web server"/>
		<SingleService name="DPI"/>	
	</Catalog>

</RootNetwork>
